apiVersion: v1
kind: Service
metadata:
  name: unity-accelerator
  labels:
    {{- include "unity-accelerator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    - port: {{ .Values.service.port }}
      targetPort: 10080
      protocol: TCP
      name: accelerator
  selector:
    {{- include "unity-accelerator.selectorLabels" . | nindent 4 }}
